# Generated by Django 5.0.2 on 2024-02-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_alter_project_image_punkt'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_projects', models.BigIntegerField()),
                ('turnover_price', models.BigIntegerField()),
                ('control_rate', models.BigIntegerField()),
                ('active_projects', models.BigIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Niyə bizi seçirlər',
                'verbose_name_plural': 'Niyə bizi seçirlər',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsPunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punkts', to='core.whychooseus')),
            ],
            options={
                'verbose_name': 'Punkt',
                'verbose_name_plural': 'Punktlar',
            },
        ),
    ]
