# Generated by Django 5.0.2 on 2024-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_process_processpunkt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Şəkil',
                'verbose_name_plural': 'Qalereya',
            },
        ),
    ]
