# Generated by Django 5.0.2 on 2024-02-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='title1',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title2',
        ),
    ]
