# Generated by Django 5.0.2 on 2024-02-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Üzv', 'verbose_name_plural': 'Komanda üzvləri'},
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to='team'),
        ),
    ]
