# Generated by Django 5.0.2 on 2024-02-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_team_options_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hero')),
                ('project_for_year', models.IntegerField(blank=True, null=True, verbose_name='Proyekt / Il')),
                ('turnover', models.BigIntegerField(blank=True, null=True, verbose_name='İllik dövriyyə')),
            ],
            options={
                'verbose_name': 'Ana səhifə | Əsas hissə',
                'verbose_name_plural': 'Ana səhifə | Əsas hissə',
            },
        ),
    ]
