# Generated by Django 5.0.2 on 2024-02-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='slogan',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
