# Generated by Django 5.0.2 on 2024-02-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comleted',
            field=models.DateField(null=True),
        ),
    ]
