# Generated by Django 5.0.2 on 2024-02-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_project_comleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='comleted',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
