# Generated by Django 5.0.2 on 2024-02-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_generalsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='mobile_logo',
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='general_settings_favicon'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='logo',
            field=models.FileField(blank=True, upload_to='general_settings_logo'),
        ),
    ]
