# Generated by Django 5.0.2 on 2024-02-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_generalsettings_mobile_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
