# Generated by Django 5.0.2 on 2024-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_service_duration_remove_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_detail_info',
            field=models.BooleanField(default=False),
        ),
    ]
