# Generated by Django 5.0.2 on 2024-05-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
