# Generated by Django 5.0.2 on 2024-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_team_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['order'], 'verbose_name': 'Üzv', 'verbose_name_plural': 'Komanda üzvləri'},
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to='team', verbose_name='image (417x603)px'),
        ),
    ]
